// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { unified } from '@astrojs/markdown-remark';
import remarkKlinos from './src/plugins/remark-klinos.mjs';
import { starlightSidebar } from './scripts/sidebar.mjs';

export default defineConfig({
	devToolbar: { enabled: false },
	// Fetch a page when its link is hovered or focused, so the page transition does not wait on the network.
	// Not "viewport": the sidebar shows ~40 links, which would download most of the site on every page view.
	prefetch: { prefetchAll: true, defaultStrategy: 'hover' },
	// The home page lives at its folder address; the bare root forwards to it.
	redirects: { '/': '/using-klinos/start-here/home/' },
	markdown: {
		// Keep the text exactly as written (no curly-quote or dash substitution).
		processor: unified({ remarkPlugins: [remarkKlinos], smartypants: false }),
	},
	integrations: [
		starlight({
			title: 'Klinos Docs',
			// Tab titles read "About Klinos - Klinos Docs"; Home sets its own ("Klinos Docs") in its frontmatter.
			titleDelimiter: '-',
			// Keeps og:title equal to the tab title.
			routeMiddleware: './src/routeData.ts',
			description: 'Documentation for Klinos, a Figma plugin for device mockups and angled cards.',
			// Lucide rotate-3d (ISC). Generated by scripts/make-favicons.mjs.
			favicon: '/favicon.svg',
			head: [
				{ tag: 'link', attrs: { rel: 'icon', href: '/favicon.ico', sizes: '16x16 32x32 48x48' } },
				{ tag: 'link', attrs: { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' } },
			],
			sidebar: starlightSidebar(),
			// Dates come from git, written into the frontmatter by scripts/sync-content.mjs.
			lastUpdated: false,
			pagination: true,
			credits: false,
			customCss: [
				'@fontsource/inter/400.css',
				'@fontsource/inter/500.css',
				'@fontsource/inter/600.css',
				'@fontsource/inter-tight/600.css',
				'@fontsource/geist-mono/400.css',
				'@fontsource/geist-mono/500.css',
				'./src/styles/tokens.css',
				'./src/styles/klinos.css',
				'./src/styles/chrome.css',
			],
			components: {
				Header: './src/components/overrides/Header.astro',
				ThemeSelect: './src/components/overrides/ThemeSelect.astro',
				PageTitle: './src/components/overrides/PageTitle.astro',
				Head: './src/components/overrides/Head.astro',
				ThemeProvider: './src/components/overrides/ThemeProvider.astro',
				MobileMenuFooter: './src/components/overrides/MobileMenuFooter.astro',
				MobileMenuToggle: './src/components/overrides/MobileMenuToggle.astro',
				MobileTableOfContents: './src/components/overrides/MobileTableOfContents.astro',
				Pagination: './src/components/overrides/Pagination.astro',
				Search: './src/components/overrides/Search.astro',
				PageFrame: './src/components/overrides/PageFrame.astro',
				Sidebar: './src/components/overrides/Sidebar.astro',
			},
			expressiveCode: {
				// Light first: it is the site's default theme.
				themes: ['github-light-default', 'github-dark-default'],
				styleOverrides: {
					borderRadius: '12px',
					borderColor: 'var(--k-line)',
					codeBackground: 'var(--k-sunk)',
					codeFontFamily: 'var(--k-font-mono)',
					codeFontSize: '14px',
					scrollbarThumbColor: 'color-mix(in srgb, var(--k-ink3) 55%, transparent)',
					scrollbarThumbHoverColor: 'var(--k-ink3)',
					uiFontFamily: 'var(--k-font-body)',
					frames: {
						editorBackground: 'var(--k-sunk)',
						terminalBackground: 'var(--k-sunk)',
						editorTabBarBackground: 'var(--k-sunk)',
						terminalTitlebarBackground: 'var(--k-sunk)',
						frameBoxShadowCssValue: 'none',
					},
				},
			},
		}),
	],
});
