// Copies the in-app guide visuals (static inline SVG in the panel's guide dialogs) out of
// demo/preview.html into src/guides/, so the docs show exactly what the panel shows.
// Re-runnable; reads demo/preview.html only. Docs reference them as ![alt](/guides/<file>),
// and src/plugins/remark-klinos.mjs inlines them (they use currentColor, so they follow the theme).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT = join(ROOT, 'src', 'guides');
const html = readFileSync(join(ROOT, 'demo', 'preview.html'), 'utf8');

/** The markup of one guide dialog, from its modal id to the next modal. */
function modal(id) {
	const start = html.indexOf(`<div class="modal" id="${id}"`);
	if (start < 0) throw new Error(`guide dialog #${id} not found in demo/preview.html`);
	const next = html.indexOf('<div class="modal"', start + 10);
	return html.slice(start, next < 0 ? undefined : next);
}
/** Every balanced <tag …>…</tag> block (tags of this name are not nested in the guides). */
function blocks(src, tag, open = `<${tag}`) {
	const out = [];
	let i = 0;
	while ((i = src.indexOf(open, i)) > -1) {
		const end = src.indexOf(`</${tag}>`, i);
		out.push(src.slice(i, end + tag.length + 3));
		i = end;
	}
	return out;
}
function one(list, what) {
	if (list.length !== 1) throw new Error(`expected one ${what}, found ${list.length}`);
	return list[0];
}

const NOTE = '<!-- Generated by scripts/extract-guides.mjs from demo/preview.html. Do not edit. -->\n';
const files = {};

// How lighting works: the light plot.
files['lighting-plot.svg'] = one(blocks(modal('lighthelpmodal'), 'svg'), 'lighting plot svg');

// Polished frame: the cross-section figure and the Shine strip.
const polish = modal('polishhelpmodal');
files['polish-frame.svg'] = one(blocks(blocks(polish, 'div', '<div class="helpfig"').join(''), 'svg'), 'polish figure svg');
files['polish-shine.html'] = one(blocks(polish, 'div', '<div class="shinestrip"'), 'polish shine strip');

// Surface texture: the grain strip.
files['grain-strip.html'] = one(blocks(modal('grainhelpmodal'), 'div', '<div class="shinestrip"'), 'grain strip');

// Using Playground: one icon per step.
const steps = blocks(modal('plhelpmodal'), 'svg');
if (steps.length !== 7) throw new Error(`expected 7 Playground step icons, found ${steps.length}`);
steps.forEach((svg, i) => (files[`playground-step-${i + 1}.svg`] = svg));

mkdirSync(OUT, { recursive: true });
for (const [name, body] of Object.entries(files)) writeFileSync(join(OUT, name), NOTE + body + '\n');
console.log(`[guides] ${Object.keys(files).length} visuals written to src/guides/`);
